export const propulsionMetricInfo: Record<string, string> = {
  "Adjusted takeoff thrust": "Static thrust corrected for the hover-efficiency model.",
  "Battery": "Selected off-the-shelf pack used for voltage, current, energy, and mass checks.",
  "Battery (Actual)": "Drawn battery mass from Sketch, mirrored only when the geometry requires it.",
  "Battery (Sizing)": "Battery mass from the Sizing estimate because no drawn battery was found.",
  "Battery current margin": "Pack current capability divided by peak mission current demand.",
  "Battery energy margin": "Selected pack energy divided by required installed mission energy.",
  "Battery mass match": "Selected pack catalogue mass compared with the drawn battery mass used in aircraft mass.",
  "Battery max current": "Pack capacity times C-rating.",
  "Best cruise speed": "Lowest-power cruise speed from the sketch aero, stall margin, and selected propeller limits.",
  "Blades (Sizing)": "Blade count from Sizing; used in rotor efficiency and mass estimates.",
  "C rating": "Maximum discharge multiplier for the pack capacity.",
  "Capacity": "Pack amp-hours before reserve and voltage conversion.",
  "Continuous power": "Motor catalogue continuous rating used for thermal margin.",
  "Cruise current": "Estimated pack current while cruising at the selected efficient speed.",
  "Cruise efficiency": "Estimated propeller efficiency in forward flight.",
  "Cruise energy left": "Usable pack energy remaining after takeoff energy is removed.",
  "Cruise driver": "What is setting the current best-cruise speed on this page.",
  "Cruise peak efficiency": "Catalogue forward-flight peak efficiency for the selected propeller.",
  "Cruise power": "Power required to overcome sketch aero drag in cruise.",
  "Diameter": "Selected propeller diameter.",
  "Diameter (Actual)": "Rotor diameter drawn in Sketch.",
  "Diameter (Sizing)": "Rotor diameter from Sizing because no drawn rotor was found.",
  "Disk area / rotor": "Swept area of one selected rotor disk.",
  "Disk loading": "Takeoff thrust divided by rotor disk area.",
  "ESC rating": "Suggested per-motor ESC current rating with headroom above the larger of prop current and mission demand.",
  "Hover efficiency": "Rotor hover efficiency estimate from disk loading and prop data.",
  "Hover power": "Power needed for vertical hover at the current mass.",
  "Hover thrust / motor": "Each motor's share of hover weight.",
  "Kv": "Motor RPM per volt before load losses.",
  "Mass (Actual)": "Current aircraft mass from Sketch.",
  "Max current": "Motor catalogue current limit.",
  "Max prop current / motor": "Estimated current per motor at maximum prop power.",
  "Max prop power / motor": "Estimated shaft power available per selected motor and prop.",
  "Min endurance (Sizing)": "Target minimum mission time to satisfy in combo ranking.",
  "Mission endurance": "Predicted mission time after takeoff energy and reserve are accounted for.",
  "Mission energy": "Installed battery energy required for takeoff plus cruise plus reserve.",
  "Motor": "Selected off-the-shelf motor used for power, current, RPM, and mass checks.",
  "Motor power margin": "Selected motor continuous power divided by peak mission demand.",
  "Operating RPM": "Estimated loaded RPM for the selected motor and propeller.",
  "Pack mass": "Catalogue battery pack mass.",
  "Peak demand / motor": "Peak electrical mission demand split across rotors.",
  "Peak electrical": "Highest electrical power demand in the mission, usually takeoff.",
  "Peak mission current": "Highest mission power divided by selected pack voltage.",
  "Per motor": "Selected system takeoff thrust split across motors.",
  "Pitch": "Selected propeller pitch; this sets pitch-speed limit behavior.",
  "Pitch speed": "Theoretical top speed from prop pitch and RPM.",
  "Propeller": "Selected off-the-shelf propeller used for thrust and efficiency checks.",
  "Reserve": "Battery percentage held back at landing.",
  "Required takeoff current": "Takeoff electrical power divided by selected pack voltage.",
  "Rotor diameter fit": "Selected prop diameter compared with the drawn or sized rotor envelope.",
  "Rotors (Actual)": "Physical rotor count inferred from drawn Sketch rotors and mirrors.",
  "Rotors (Sizing)": "Rotor count from Sizing because no drawn rotor count was found.",
  "Max pack current used": "Total pack current drawn by the selected motor/prop combination at maximum prop power.",
  "Prop data source": "Whether the selected prop sample is based on a measured table or a rough estimate.",
  "Prop speed margin": "Full-command prop pitch speed divided by the minimum flyable cruise speed.",
  "Static thrust": "Catalogue static thrust for the selected propeller at its test RPM.",
  "Takeoff energy": "Peak takeoff power multiplied by takeoff/hover allowance.",
  "Takeoff electrical": "Electrical power required for the target takeoff thrust-to-weight.",
  "Takeoff thrust / weight": "Available takeoff thrust divided by aircraft weight.",
  "Takeoff T/W margin": "Available takeoff thrust-to-weight divided by the target thrust-to-weight.",
  "Takeoff time": "Hover/takeoff/landing allowance from Sizing.",
  "Target T/W": "Vertical takeoff thrust-to-weight target.",
  "Target T/W (Sizing)": "Vertical takeoff thrust-to-weight target from Sizing.",
  "Total available shaft": "Total shaft power across all selected motors.",
  "Usable energy after reserve": "Selected pack energy minus the landing reserve.",
  "Voltage": "Nominal pack voltage from cell count at 3.7 V per cell.",
};
