export const jetMetricInfo: Record<string, string> = {
  "Added jet mass": "Engine plus fuel mass added to the base aircraft.",
  "Aircraft with jets": "Base aircraft plus selected engine and fuel package.",
  "Assisted prop power": "Prop electrical power after jet thrust replaces part of the prop thrust at the target speed.",
  "Base cruise power": "Prop-only electrical power at the base best-cruise speed.",
  "Base endurance": "Prop-only endurance at the base best-cruise speed.",
  "Base range": "Prop-only range at the base best-cruise speed.",
  "Best cruise endurance": "Prop-only cruise time at the best flyable cruise speed before adding jets and fuel.",
  "Best cruise power": "Electrical cruise power used at the best flyable cruise speed.",
  "Best cruise prop": "Best-cruise power as a percent of full prop power, with the cube-law equivalent prop command.",
  "Best cruise range": "Prop-only cruise distance at the best flyable cruise speed before adding jets and fuel.",
  "Best cruise speed": "Lowest-power flyable cruise speed from the base aircraft aero and selected propeller.",
  "Battery": "Battery state of charge at this condition.",
  "Battery draw": "Electrical power and pack current required at this command.",
  "Battery mass": "Battery mass from the selected or drawn power source.",
  "Battery time": "Time until the battery reaches reserve at this command.",
  "Best jet command": "Jet command at the best matched iJet point.",
  "Best endurance": "Longest endurance found by holding base cruise speed and using jet thrust to reduce prop power.",
  "Best prop command": "Prop command at the best matched iJet point.",
  "Best range": "Longest range found in the command sweep.",
  "Battery cap": "Total pack current available from the selected battery.",
  "Cap mode": "Which system limits the prop command in the iJet mixer.",
  "Command": "Motor and jet command percentage for this selected condition.",
  "Dry mass": "Hybrid aircraft mass after usable fuel is gone.",
  "Endurance": "Usable flight time until the first limiter is reached.",
  "Endurance gain": "Endurance increase versus the base prop-only best-cruise case.",
  "Endurance range": "Distance covered at the fixed target speed for the endurance-assist case.",
  "Engine": "Kerosene turbine selected from the Sizing engine list.",
  "Engine + fuel": "Combined mass of both turbines plus planned fuel.",
  "Engine mass": "Mass of the selected turbines.",
  "Engines": "Physical turbine count used in the hybrid model.",
  "Error": "Battery-time and fuel-time mismatch at the iJet solved point.",
  "Fuel": "Fuel state at this condition.",
  "Fuel at full command": "Fuel load expressed as minutes of full-command turbine burn.",
  "Fuel burn": "Total fuel flow for both turbines at this command.",
  "Fuel mass": "Kerosene mass from selected burn time and turbine flow.",
  "Fuel remaining": "Fuel reserve left at the landing case.",
  "Fuel time": "Time until fuel reaches reserve at this command.",
  "Hybrid T/W": "Prop plus jet thrust divided by aircraft weight.",
  "Hybrid battery": "Battery current for takeoff with jets contributing thrust.",
  "Hybrid command": "Motor+jet command needed to hit the takeoff target.",
  "Hybrid excess": "Hybrid thrust margin above the takeoff target.",
  "Hybrid mass": "Aircraft mass for the hybrid case at this fuel state.",
  "Hybrid required": "Thrust required for the target hybrid takeoff T/W.",
  "Jet command": "Turbine command solved by iJet for matched endurance.",
  "Jet at prop cap": "Jet command reached when prop command hits the battery or motor current cap.",
  "Jet max command": "Maximum turbine command available after prop command is capped.",
  "Jet thrust": "Turbine thrust used to reduce required prop thrust at the target speed.",
  "Limiter": "Whether battery or fuel runs out first.",
  "Matched points": "How many iJet command samples make battery and fuel time agree.",
  "Power source": "Battery selection feeding the prop-only and hybrid calculations.",
  "Pinned command": "Hybrid command pinned to the prop-only best-cruise command.",
  "Power draw": "Electrical power and pack current required at this command.",
  "Prop command": "Motor command percentage used as the iJet independent input.",
  "Prop cap": "Maximum prop command before the selected battery or motor current limit is reached.",
  "Prop-only T/W": "Prop thrust divided by aircraft weight with jets excluded.",
  "Prop-only battery": "Battery current for prop-only takeoff.",
  "Prop-only command": "Motor command needed for prop-only takeoff target.",
  "Prop-only excess": "Prop-only thrust margin above the takeoff target.",
  "Prop-only mass": "Aircraft mass without active jet thrust for the comparison case.",
  "Prop-only required": "Thrust required for the prop-only takeoff target.",
  "Range": "Distance in nautical miles at this speed and endurance.",
  "Range gain": "Range increase versus the base prop-only best-cruise case.",
  "Speed": "Predicted forward speed in knots at this command.",
  "Status": "Whether iJet could balance battery time and fuel time.",
  "Split ratio": "Jet command divided by prop command from the Endurance best split.",
  "Takeoff T/W": "Available takeoff thrust-to-weight after hover-efficiency and power limits.",
  "Target speed": "Base aircraft best-cruise speed held fixed for the endurance calculation.",
  "Total jet thrust": "Full-command thrust from all selected turbines.",
  "Total mass": "Aircraft mass for the current comparison case.",
  "Total thrust": "Prop plus jet thrust at the selected command.",
  "Vs best-cruise endurance": "Hybrid endurance gain versus the base aircraft at best cruise.",
  "Vs best-cruise range": "Hybrid range gain versus the base aircraft at best cruise.",
  "Vs best-cruise speed": "Hybrid speed gain versus the base aircraft at best cruise.",
};
