export const jetMetricInfo: Record<string, string> = {
  "Added jet mass": "Engine plus fuel mass added to the base aircraft.",
  "Assisted prop power": "Prop electrical power after jet thrust replaces part of the prop thrust at the target speed.",
  "Base cruise power": "Prop-only electrical power at the base best-cruise speed.",
  "Base endurance": "Prop-only endurance at the base best-cruise speed.",
  "Base range": "Prop-only range at the base best-cruise speed.",
  "Best cruise endurance": "Prop-only cruise time at the best flyable cruise speed before adding jets and fuel.",
  "Best cruise power": "Electrical cruise power used at the best flyable cruise speed.",
  "Best cruise prop": "Best-cruise power as a percent of full prop power, with the cube-law equivalent prop command.",
  "Best cruise range": "Prop-only cruise distance at the best flyable cruise speed before adding jets and fuel.",
  "Best cruise speed": "Lowest-power flyable cruise speed from the base aircraft aero and selected propeller.",
  "Battery": "Battery state of charge at this condition.",
  "Battery draw": "Electrical power and pack current required at this command.",
  "Battery mass": "Battery mass from the selected or drawn power source.",
  "Battery time": "Time until battery reserve; Endurance integrates changing mass as fuel burns.",
  "Best endurance": "Longest time found after burning fuel step-by-step and recomputing mass, drag, and prop power.",
  "Best endurance mix": "Command and limiter for the longest flight-time point in the endurance sweep.",
  "Best range": "Longest distance found in the endurance sweep, using speed times integrated flight time.",
  "Best speed": "Airspeed at the selected best-endurance or best-range point, shown in knots.",
  "Command": "Motor and jet command percentage for this selected condition.",
  "Constraint": "Rule the optimizer must satisfy before choosing a better split.",
  "Cruise command": "Command used for the pinned cruise comparison.",
  "Detailed endurance": "Integrated flight time after fuel burn changes aircraft mass and drag.",
  "Dry mass": "Hybrid aircraft mass after usable fuel is gone.",
  "Endurance": "Usable flight time until battery or fuel reserve is reached.",
  "Endurance gain": "Endurance increase versus the base prop-only best-cruise case.",
  "Endurance range": "Distance covered at the fixed target speed for the endurance-assist case.",
  "Engine": "Kerosene turbine selected from the Sizing engine list.",
  "Engine + fuel": "Combined mass of both turbines plus planned fuel.",
  "Engine mass": "Mass of the selected turbines.",
  "Engines": "Physical turbine count used in the hybrid model.",
  "Fuel": "Fuel state at this condition.",
  "Fuel at full command": "Fuel load expressed as minutes of full-command turbine burn.",
  "Fuel burn": "Total fuel flow for both turbines at this command.",
  "Fuel mass": "Kerosene mass from selected burn time and turbine flow.",
  "Fuel remaining": "Fuel reserve left at the landing case.",
  "Fuel time": "Time until fuel reaches reserve at this command.",
  "Goal": "What the optimizer is trying to improve after constraints are met.",
  "Hybrid T/W": "Prop plus jet thrust divided by aircraft weight.",
  "Hybrid battery": "Battery current for takeoff with jets contributing thrust.",
  "Hybrid command": "Motor+jet command needed to hit the takeoff target.",
  "Hybrid excess": "Hybrid thrust margin above the takeoff target.",
  "Hybrid required": "Thrust required for the target hybrid takeoff T/W.",
  "Jet command": "Turbine throttle command. 0% is idle, not off.",
  "Jet thrust": "Turbine thrust used to reduce required prop thrust at the target speed.",
  "Limiter": "Whether battery or fuel runs out first.",
  "Mass": "Aircraft mass for this takeoff or landing comparison row.",
  "Mode": "How this row's prop and jet commands were chosen.",
  "Power source": "Battery selection feeding the prop-only and hybrid calculations.",
  "Power draw": "Electrical power and pack current required at this command.",
  "Base T/W": "Prop-only aircraft takeoff thrust-to-weight at prop-only aircraft mass.",
  "Prop command": "Motor command percentage used as the iJet independent input.",
  "Prop thrust": "Average prop thrust required after jet thrust is subtracted.",
  "Prop-only T/W": "Prop thrust divided by aircraft weight with jets excluded.",
  "Prop-only battery": "Battery current for prop-only takeoff.",
  "Prop-only command": "Motor command needed for prop-only takeoff target.",
  "Prop-only excess": "Prop-only thrust margin above the takeoff target.",
  "Prop-only required": "Thrust required for the prop-only takeoff target.",
  "Range": "Distance in nautical miles at this speed and endurance.",
  "Range gain": "Range increase versus the base prop-only best-cruise case.",
  "Search": "Variables the optimizer is allowed to change.",
  "Speed": "Predicted forward speed in knots at this command.",
  "Split ratio": "Jet command divided by prop command from the Endurance best split.",
  "Takeoff T/W": "Available takeoff thrust-to-weight after hover-efficiency and power limits.",
  "Target T/W": "Vertical takeoff thrust-to-weight target from Sizing.",
  "T/W boost": "Hybrid aircraft takeoff thrust-to-weight minus base prop-only aircraft takeoff thrust-to-weight.",
  "Target speed": "Base aircraft best-cruise speed held fixed for the endurance calculation.",
  "Total jet thrust": "Full-command thrust from all selected turbines.",
  "Total mass": "Aircraft mass for the current comparison case.",
  "Total thrust": "Prop plus jet thrust at the selected command.",
  "Vs best-cruise range": "Hybrid range gain versus the base aircraft at best cruise.",
  "Vs best-cruise speed": "Hybrid speed gain versus the base aircraft at best cruise.",
};
