export const computeMetricInfo: Record<string, string> = {
  "Actual usable": "Usable battery energy from the drawn battery mass after reserve.",
  "Aero center X": "MachUpX aerodynamic center on the nose-forward X axis.",
  "Aero center Z": "MachUpX vertical aerodynamic-center location.",
  "Alpha high": "Upper angle-of-attack sample used when MachUpX cannot hit target CL.",
  "Alpha low": "Lower angle-of-attack sample used when MachUpX cannot hit target CL.",
  "Alpha zero": "MachUpX lift sample at zero degrees angle of attack.",
  "Added stall margin": "How much extra CLmax margin the current Wingevon, LEX, and blown-wing effects add at cruise.",
  "Applied stall speed": "Stall speed after applying Wingevon, LEX vortex lift, and rotor-blown wing lift estimates.",
  "Aspect ratio": "Span squared divided by wing area; higher usually lowers induced drag.",
  "Best endurance": "Speed with the lowest cruise power in the speed sweep.",
  "Best range": "Speed with the best distance per watt-hour in the speed sweep.",
  "CD estimate": "Induced plus parasite drag estimate for the drawn aircraft.",
  "CD induced": "Drag caused by making lift; rises quickly with high wing loading.",
  "CD parasite": "Baseline drag from bodies, surfaces, rotors, and blunt shapes.",
  "CD total": "Induced plus parasite drag used for drag and cruise power.",
  "CD total vs speed": "How total drag coefficient changes across the speed sweep.",
  "CL at zero alpha": "MachUpX lift coefficient at zero degrees angle of attack.",
  "CL cruise": "Lift coefficient needed at the current cruise speed and mass.",
  "CL high": "MachUpX lift coefficient at the upper sampled angle.",
  "CL low": "MachUpX lift coefficient at the lower sampled angle.",
  "CL alpha": "MachUpX lift-curve slope; more means lift grows faster with angle of attack.",
  "CL required": "Lift coefficient required at cruise to carry the current mass.",
  "Clean stall speed": "Baseline stall speed before Wingevon, LEX vortex lift, or rotor-blown wing lift is applied.",
  "Blown q ratio": "Estimated dynamic-pressure increase on wing area inside rotor disks.",
  "Blown wing area": "Wing planform area covered by rotor disks and treated as powered-lift area.",
  "Blown wing stall margin": "Estimated stall-speed reduction and CLmax gain from rotor slipstream over the wing alone.",
  "CLmax": "Assumed maximum lift coefficient from airfoil, Wingevon, LEX, and rotor-blown wing heuristics.",
  "CLmax for 25 kt": "CLmax required for the current mass and wing area to stall at 25 kt, plus the margin from the current applied CLmax.",
  "CLmax for 30 kt": "CLmax required for the current mass and wing area to stall at 30 kt, plus the margin from the current applied CLmax.",
  "Cm at AC": "Pitching moment coefficient about the MachUpX aerodynamic center.",
  "CoM X": "Longitudinal center of mass on the nose-forward X axis.",
  "CoP X": "Fast-solver aerodynamic center on the nose-forward X axis.",
  "Cruise power": "Power needed to overcome estimated drag at cruise.",
  "Cruise speed": "Sizing cruise target, always shown in knots.",
  "Cruise target": "The cruise speed currently requested by Sizing.",
  "Dihedral": "Average wing up/down angle; feeds roll stability.",
  "Dihedral effect": "Heuristic roll-restoring index from dihedral/anhedral and wing layout.",
  "Disk loading": "Weight divided by rotor disk area; lower is easier for hover.",
  "Drag": "Estimated aerodynamic force opposing cruise.",
  "Drag / power overlay": "Drag and power curves on the same speed axis.",
  "Drag reference area": "Area used to turn drag coefficient into newtons of drag.",
  "Dynamic pressure": "Air pressure available at cruise; scales with speed squared.",
  "Endurance vs speed": "Predicted flight time at each speed using available battery energy.",
  "Fin area": "Total mirrored vertical fin area counted for yaw authority.",
  "Fin arm": "Distance from wing aerodynamic center to fin aerodynamic center.",
  "Flight regime": "Current cruise CL compared against clean CLmax and high-lift CLmax: Flying, High AoA, or Stalled.",
  "Full stall speed": "Speed where even the high-lift model cannot carry the current mass.",
  "High-AoA band": "Speed band where the main wing is past clean stall but Wingevon, LEX, and blown-wing effects may still carry the aircraft.",
  "Horizontal tail volume": "Pitch authority from tail area and arm, normalized by wing area and mean chord.",
  "Hover power": "Ideal hover power adjusted by rotor figure of merit.",
  "Hover thrust / rotor": "Each physical rotor's share of aircraft weight in hover.",
  "Induced drag share": "Percent of total drag caused by lift at each speed.",
  "L/D": "Lift-to-drag ratio; higher means less cruise power.",
  "L/D vs speed": "Efficiency curve across the speed sweep.",
  "LEX area": "Leading-edge extension area treated as vortex-lift geometry.",
  "LEX influenced body": "Body area inside the LEX influence zone.",
  "LEX influenced wing": "Wing area inside the LEX influence zone.",
  "LEX stall margin": "Estimated stall-speed reduction and CLmax gain from the LEX alone.",
  "LEX vortex strength": "Heuristic strength of the LEX lift boost.",
  "MachUpX CL": "Lift coefficient solved by MachUpX from lifting surfaces only.",
  "MachUpX L/D": "MachUpX lifting-surface lift-to-drag ratio.",
  "MachUpX alpha": "Angle of attack MachUpX solved for the target CL.",
  "MachUpX lifting CD": "MachUpX lifting-surface drag coefficient, excluding body parasite drag.",
  "MachUpX static margin": "MachUpX aerodynamic center compared with sketch CoM.",
  "MachUpX status": "Whether the external lifting-line solve has a valid result.",
  "Mass": "Total sketch mass from bodies, parts, batteries, rotors, motors, and mirrors.",
  "Max Reynolds": "Highest section Reynolds number reported by MachUpX.",
  "Max section CL": "Most heavily loaded section reported by MachUpX.",
  "Mean chord": "Wing area divided by span; used for stability and Reynolds scale.",
  "Min fly speed": "Stall speed with the current safety margin applied.",
  "Pitch damping": "MachUpX pitch-rate damping derivative; more negative is stronger damping.",
  "Pitch inertia": "Resistance to nose-up/nose-down acceleration from mass lengthwise.",
  "Pitch stability": "Static-margin judgement for longitudinal stability.",
  "Pitch stability Cm alpha": "MachUpX pitch stability derivative; negative is stable.",
  "Pitch trim": "Whether MachUpX found a pitch-trim path with available controls.",
  "Projected span": "Tip-to-tip span in top view.",
  "Range vs speed": "Predicted distance at each speed using available battery energy.",
  "Roll damping": "MachUpX roll-rate damping derivative; more negative is stronger damping.",
  "Roll inertia": "Resistance to roll acceleration from mass spread across span.",
  "Roll stability": "Plain-English roll-stability judgement from dihedral effect.",
  "Roll stability Cl beta": "MachUpX roll response to sideslip; negative usually means stabilizing dihedral effect.",
  "Rotor disk area": "Total swept disk area for all physical rotors.",
  "Rotors": "Physical rotor count after mirrors.",
  "Sizing usable": "Usable battery energy implied by Sizing when no drawn battery exists.",
  "Solved surfaces": "Number of lifting surfaces MachUpX accepted for the solve.",
  "Stall estimate": "Estimated stall speed from weight, wing area, and CLmax.",
  "Stall AoA": "Estimated aircraft angle of attack where the wing reaches CLmax, using selected airfoil lift slope and incidence. First-pass only.",
  "Stall margin": "CLmax divided by required CL at each speed; 1.0 is stall.",
  "Static margin": "CoM ahead of aerodynamic center as percent of mean chord.",
  "Tail arm": "Distance from wing aerodynamic center to tail aerodynamic center.",
  "Tail volume": "Horizontal tail authority from tail area, arm, wing area, and mean chord.",
  "Tailplane area": "Total mirrored horizontal tail area counted for pitch authority.",
  "Target CL": "Lift coefficient MachUpX is trying to solve.",
  "True span": "3D span including dihedral/anhedral.",
  "Vertical fin volume": "Yaw authority from fin area and arm, normalized by wing area and span.",
  "Wing area": "Mirrored wing lifting-surface planform area.",
  "Wingevon area": "All-moving wing-tip area counted as wing area and treated as floating with local relative airflow at low speed.",
  "Wingevon effective AoA": "First-pass aircraft AoA where the main wing stalls after blending fixed-wing AoA with floating Wingevon local AoA.",
  "Wingevon stall margin": "Estimated stall-speed reduction and CLmax gain from the all-moving wing-tip area alone.",
  "Wing loading": "Mass divided by wing area; drives stall and cruise CL.",
  "Yaw damping": "MachUpX yaw-rate damping derivative; more negative is stronger damping.",
  "Yaw inertia": "Resistance to heading acceleration from mass spread in planform.",
  "Yaw stability": "Vertical fin volume coefficient used as a yaw-stability proxy.",
  "Yaw stability Cn beta": "MachUpX yaw response to sideslip; positive usually means weathercock stability.",
};
