export const sizingMetricInfo: Record<string, string> = {
  "Actual L/W": "Computed total length divided by total width. This should match Length Ratio unless packaging or tail geometry needs more room.",
  "Actual aspect ratio": "Final span squared divided by wing area. Can exceed your Aspect Ratio input if rotor clearance widens the span.",
  "Actual cruise CL": "Lift coefficient required at the final mass, cruise speed, and wing area. It can differ from your target if the wing-loading cap sizes the wing.",
  "Area driver": "Whether wing area came from target cruise CL or from the 34 kg/m2 wing-loading cap.",
  "Battery L x W x H": "Package estimate from pack mass, 1700 kg/m3 LiPo density, and chosen pack aspect ratio. Packaging guidance only.",
  "Battery mass": "Installed pack energy divided by battery energy density. Discharge/current capability is checked later in Propulsion.",
  "Cruise energy": "Cruise power multiplied by target cruise endurance.",
  "Cruise L/D": "Fixed lift-to-drag assumption used only for first-pass sizing cruise power.",
  "Cruise / stall": "Cruise speed divided by estimated stall speed. Bigger gives more stall margin at cruise.",
  "Cruise power": "Uses weight / L/D at cruise speed, with L/D fixed at 8.2 and propulsive efficiency fixed at 0.72.",
  "Cruise propulsive efficiency": "Fixed propulsive efficiency assumption used in the sizing cruise-power estimate.",
  "Electronics": "Larger of 0.90 kg or 0.55 kg avionics + 0.15 kg/motor + 0.075 kg/kW takeoff HV electronics.",
  "Estimated mass": "Iterated all-up estimate: payload, battery, motors, rotors, electronics, and G-rated structure heuristic.",
  "Fin aerofoil": "Symmetric section for yaw stability with minimal side-force bias.",
  "Fin area / fin": "Total vertical fin area split across two fins.",
  "Fin area total": "From fin volume ratio, wing area, wingspan, and tail arm, then split across two fins.",
  "Fin height x chord": "Fin dimensions from area, using a simple height/chord proportion. Not a structural or stall check.",
  "Fin volume ratio": "Vertical tail volume coefficient using total fin area, tail arm, wing area, and wingspan. Sizing target is 0.04.",
  "Energy density": "Sizing assumption for LiPo pack-level energy density. Default is 190 Wh/kg.",
  "Flight target": "Cruise minutes plus hover allowance before reserve is applied.",
  "Hover energy": "Takeoff power multiplied by hover allowance. This covers VTOL takeoff/landing allowance.",
  "Fuselage pod L x W": "Battery package plus payload bay plus clearance. Payload bay assumes about 1000 kg/m3 and 70% use of the pod cross-section.",
  "Hover figure of merit": "Rotor hover efficiency assumption used in momentum theory. More blades use a lower figure here.",
  "Hover power": "Total hover power from momentum theory. Figure of merit is 0.62 for 2 blades, 0.60 for 3, 0.56 for 4.",
  "Hover power / motor": "Total hover power split across the two rotors.",
  "Ideal rotor diameter": "Diameter from target disk loading before the blade-count diameter adjustment.",
  "Length driver": "The rule currently setting total length: your Length Ratio, the payload/battery pod, or tail geometry.",
  "Mass / motor": "Catalogue motor mass, or scaled by 5200 W/kg takeoff power and thrust margin if the sample is too small.",
  "Motor basis": "Reference catalogue motor used as the scaling starting point. Large aircraft may be an estimate beyond this motor.",
  "Stall CLmax": "Clean finite-wing CLmax assumed from the suggested airfoil. It is not flap, propwash, Reynolds, or post-stall modelling.",
  "Installed pack energy": "Required total battery energy so mission energy is used while landing with the reserve percentage still in the pack.",
  "Mission energy": "Cruise energy plus hover energy before landing reserve.",
  "Motor diameter": "Catalogue motor diameter, scaled with motor mass if power demand exceeds the sample motor.",
  "Motor length": "Catalogue motor length, scaled with motor mass if power demand exceeds the sample motor.",
  "Motor mass driver": "Which rule set the motor estimate: catalogue minimum, takeoff power, or thrust target.",
  "Payload": "Mission input payload carried as useful load. Included directly in estimated mass.",
  "Payload bay length": "Rough package length for payload mass. Assumes about 1000 kg/m3 and 70% use of a square pod cross-section.",
  "Reference thrust / motor": "Catalogue static thrust of the reference motor before any sizing scale-up.",
  "Reserve": "Battery percentage intentionally left unused at landing.",
  "Reserve energy": "Installed pack energy minus mission energy.",
  "Rotor diameter": "Diameter from disk-loading target, reduced for extra blades by a simple exponent. Minimum ideal diameter is 0.25 m.",
  "Rotor mass": "Two carbon fibre rotors. Scales sample blade mass by diameter^2.15 and blade count; no RPM, root stress, or blade stiffness check.",
  "Resulting disk loading": "Takeoff thrust per suggested rotor disk area after blade-count diameter adjustment.",
  "Sizing thrust / motor": "Per-motor takeoff thrust target with sizing margin. This is a requirement, not catalogue proof.",
  "Stall speed": "Uses mass, wing area, and airfoil CLmax guesses: S1223 1.8, Clark Y 1.45, NACA 2412 1.5, others 1.25.",
  "Structure": "Base is 25% of payload + battery + motors + rotors + electronics, scaled by (G-rating / 2)^0.6. Not a span/load structural analysis.",
  "Suggested aerofoil": "Rule pick from cruise speed and cruise CL. It is not CFD or airfoil optimization.",
  "Suggested rotor diameter": "Rotor diameter after the blade-count diameter adjustment. It feeds the suggested sketch.",
  "Tail aerofoil": "Symmetric tail section for predictable pitch stability.",
  "Tail arm": "Wing-to-tail distance. At least 1.35x mean chord or 0.46x rotor diameter.",
  "Tail arm driver": "Whether tail arm is set by the minimum-control-arm rule or by your Length Ratio target.",
  "Tail area / tailplane": "Area for each horizontal tailplane after splitting total tail area.",
  "Tail area total": "Uses tail volume target 0.55, wing area, mean chord, and tail arm; then splits across two tailplanes.",
  "Tailplane AR": "Aspect ratio of one horizontal tailplane after its span is capped to the rotor wake diameter.",
  "Tailplane span x chord": "One tailplane package. Span is capped at rotor diameter so the surface stays in the rotor wake.",
  "Tail volume ratio": "Horizontal tail volume coefficient using total tailplane area, tail arm, wing area, and mean chord. Sizing target is 0.55.",
  "Takeoff power": "Hover power multiplied by Takeoff T/W^1.5.",
  "Takeoff power / motor": "Total takeoff power split across the two rotors. This drives the motor mass estimate.",
  "Takeoff thrust / motor": "Target vertical takeoff thrust split across the two motors.",
  "Target disk loading": "Best-guess takeoff disk loading from cruise speed, endurance, and hover allowance before blade-count adjustment.",
  "Target T/W": "Vertical thrust-to-weight target from the mission input.",
  "Target length": "Total width multiplied by your Length Ratio input.",
  "Total length": "Nose to tail: wing root depth plus tail arm plus tail chord.",
  "Total width": "Overall planform width. In this sizing draft it equals wingspan because rotor disks are kept inside the wing span.",
  "Total motor mass": "Two motors. Each uses catalogue mass or scaled mass when takeoff power/thrust demand exceeds the sample.",
  "Total takeoff thrust": "Aircraft weight multiplied by target T/W.",
  "Vertical fins": "Fixed count for the dual-empennage concept.",
  "Wing area": "Larger of lift-required area and wing-loading cap. Wing loading is capped at 34 kg/m2.",
  "Wing chord": "Wing area divided by span after any rotor-containment span increase.",
  "Wing loading": "Mass divided by wing area. Sizing caps this at 34 kg/m2 before geometry constraints.",
  "Wing root depth": "Half of the larger of fuselage length or mean chord; measured from the nose.",
  "Width driver": "Whether width came from wing area and Aspect Ratio, or was widened to keep the rotors inside the span.",
  "Wingspan": "From wing area and Aspect Ratio, but widened if needed to contain both rotors and battery width.",
};
